#!/bin/sh


git config --global user.name "lcgrpreading"
git config --global user.email "lcgrp_reading@163.com"
git init
git add --all
git commit -m "commit"
git remote add origin git@github.com:lcgrpreading/bigfile.git
git push -u origin master